// src/constants/notificationEvents.js

export const NOTIFICATION_EVENTS = {
  CHAT_REQUESTED: "CHAT_REQUESTED",
  CHAT_ACCEPTED: "CHAT_ACCEPTED",

  CALL_RINGING: "CALL_RINGING",
  CALL_ACCEPTED: "CALL_ACCEPTED",
  CALL_MISSED: "CALL_MISSED",
  CALL_ENDED: "CALL_ENDED",

  LOW_BALANCE: "LOW_BALANCE",
};
